---
title: "Final Project: Add title here"
output:
  pdf_document: default
---




<!--  

This is a template for creating your final project write-up. It lays out the sections that should be in your write-up and describes a little about these sections. Overall your write-up should be between 5-10 pages long and should contain:

    1) Introduction: 
      - what question you are addressing
      - why is the question important 
      - where did you get the data from 
    
    2) Plots of the data
      - one or more plots
    
    3) Hypothesis tests: 
      - go through all 5 steps of a randomization test. 
      - also run a parametric test
    
    4) Confidence intervals: 
      - calculated using the bootstrap
      - also use a parametric method. 
    
    5) Conclusions: 
      - what did you find
      - future directions
      - anything else you want to discuss
    
    6) Reflection: 
      - what went well
      - what did you struggle with
      - what analyses did you do that you are not including
      - anything else you want to mention about the learning process, etc.

    7) Appendix (optional): 
      - if there is additional code you would like to include (in order to ensure your project is less than 10 pages) you can create an appendix that has this code. 
      - having this section is not necessary however


Make sure that your write-up looks good! Using additional R Markdown features can help with this, and so some useful websites are:

1)  https://www.rstudio.com/wp-content/uploads/2015/03/rmarkdown-reference.pdf
2)  https://www.rstudio.com/wp-content/uploads/2015/02/rmarkdown-cheatsheet.pdf


--> 






<!-- There are some options that will make your document look better  -->
```{r message=FALSE, warning=FALSE, tidy=TRUE, echo=FALSE}
    
    library(knitr)

    library(ClassTools)

    # makes sure the code is wrapped to fit when it creats a pdf
    opts_chunk$set(tidy.opts=list(width.cutoff=60))   
    set.seed(1)  # set the random number generator to always give the same sequence of random numbers
    
    
```







$\\$









## Introduction 


<!--  

Write ~1-3 paragraphs describing:

1) What problem you are addressing and why the problem you are addressing is interesting

2) Where you got the data from, including a link to the website where you got the data if applicable 

3) What other analyses have already been done with the data and possibly links to other analyses 

--> 





   
$\\$   
   
    




## Results




$\\$
    




### Plot the data: Change the subtitle here to describe what you are plotting


<!--  

Create one or more plots of your data. Describe the plot(s), what they show, and why they are of interest to your question. Include the code to create these plots in the R chunk below. You can also discuss the plots after the code section. 

--> 




```{r message=FALSE, warning=FALSE, tidy=TRUE}




```




<!--  

Possible additional discussion of the plots here. 

--> 








$\\$    
    







    

### Hypothesis tests: Sub-title about what the tests consist of

<!--  

Run through a hypothesis tests on your data using computational resampling methods, as well as parametric methods. For the resampling methods, please be sure to complete all 5 steps of the 5 step procedure discussed in class, and include your code in the R chunk below. For the parametric test, make sure that you get the same result (i.e., a similar p-value) or if you don't, explain why you think these types of tests differ.

--> 




```{r message=FALSE, warning=FALSE, tidy=TRUE}




```


<!--  

Possible additional discussion of the 5-step procedure and hypothesis tests here. 

--> 








$\\$      
    
    
    
    
    
    
    
    

### Confidence intervals: Sub-title about what the confidence consist of

<!--  

Calculate a confidence interval using the bootstrap and parametric methods. Interpret what the confidence interval is telling you about your question of interest, and include your code in the R chunk below. 

--> 



```{r message=FALSE, warning=FALSE, tidy=TRUE}




```


<!--  

Possible additional discussion of the confidence intervals here. 

--> 









$\\$


    
    
    
    
    
    


## Conclusion 

<!--  

1-3 paragraphs summarizing what you found, how the findings address your question of interest and possible future directions. 

-->










$\\$







## Reflection  



<!--  


Write 1-3 paragraphs describing what went well with this project and what was more difficult. Also describe any additional things you tried that you did not end up including in this write-up, and approximately how much time you spend working the project. 

Finally, please go to Canvas and answer a few questions related to how this project went: https://yale.instructure.com/courses/55573/quizzes/23898



-->





$\\$





## Appendix


<!--  


You can include additional code here if you could not fit it into the body of the document. Make sure your code is well commmented and easy read.


-->

